add_newline = true
palette = "catppuccin_mocha"

format = """
[](surface0)\
$os\
[  ](bg:lavender fg:surface0)\
$username\
[  ](bg:lavender fg:surface0 dimmed)\
$hostname\
[  ](bg:peach fg:lavender)\
$directory\
[](bg:green fg:peach)\
$git_branch\
$git_status\
[](fg:green)\
$fill\
$all\
$line_break\
$character
"""

[fill]
symbol = '·'
style = 'crust'

[directory]
style = "bg:peach fg:surface0"
format = "[$path ]($style)[$read_only]($read_only_style)"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "./"

[git_branch]
symbol = " "
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "bg:green fg:peach"

[git_commit]
disabled = true

[git_status]
format = '([$all_status$ahead_behind]($style))'
conflicted = " "
ahead = "⇡ "
behind = "⇣ "
diverged = "⇕ "
untracked = " "
stashed	= " "
modified = " "
staged = "󰆧 "
renamed	= ""
deleted	= ""
typechanged	= ""
up_to_date = " "
style = "bg:green fg:peach"

[username]
show_always = true
format = '[$user]($style)'
style_root = 'bg:lavender'
style_user = 'bg:lavender'

[hostname]
ssh_only = false
ssh_symbol = ''
format = '[$ssh_symbol$hostname]($style)'
style = 'bg:lavender'
aliases = { "Quentins-MacBook-Air" = "macbook" }

[cmd_duration]
min_time = 2_000
format = "[  $duration ]($style)"
style = "white"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[mise]
disabled = false
